import type { Metadata } from "next";
import { Geist, Geist_Mono, Cormorant } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorant = Cormorant({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const brandonGrotesque = localFont({
  src: [
    {
      path: "./fonts/BrandonGrotesque-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/BrandonGrotesque-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/BrandonGrotesque-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/BrandonGrotesque-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-brandon-grotesque",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${cormorant.variable} ${brandonGrotesque.variable} antialiased`}>
      <body
        
      >
        {children}
      </body>
    </html>
  );
}